web2/config/urls.py
from django.contrib import admin
from django.urls import path
import board.views
import user.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/create', board.views.create),
    path('board/read/<int:num>', board.views.read),
    path('board/update/<int:num>', board.views.update),
    path('board/delete/<int:num>', board.views.delete),
    path('board/list/', board.views.list),
    path('user/signup/', user.views.signup),
    path('user/login', user.views.login),
    path('user/logout', user.views.logout),

]

web2/board/models.py
from django.db import models
from django.contrib.auth.models import User
class Board(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    contents = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    def __str__(self): return self.title
# Create your models here.

web2/user/models.py
from django.db import models

# Create your models here.

web2/board/forms.py
from django import forms
from .models import Board

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'contents')

web2/board/views.py
from django.shortcuts import render
from board.forms import BoardForm
from django.shortcuts import redirect
from board.models import Board
from django.db.models import Q
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/user/login')
def create(request):
    if request.method == "GET":
        boardForm = BoardForm()
        return render(request, 'board/create.html', {'boardForm' : boardForm})
    else:
        boardForm = BoardForm(request.POST)

        if boardForm.is_valid():
            board = boardForm.save(commit=False)
            board.writer = request.user
            board.save()
            return redirect('/board/list')

def read(request, num):
    post = Board.objects.get(Q(id=num))

    return render(request, 'board/read.html', {'post':post})
@login_required(login_url='/user/login')
def update(request, num):
    post = Board.objects.get(Q(id=num))

    if request.user != post.writer:
        return redirect('/board/list/')

    if request.method == 'GET':
        boardForm = BoardForm(instance = post)
        return render(request, 'board/update.html', {"boardForm":boardForm})
    else:
        boardForm = BoardForm(request.POST)

        if boardForm.is_valid():
            post.title = boardForm.cleaned_data['title']
            post.contents = boardForm.cleaned_data['contents']
            post.save()
            return redirect("/board/read/"+str(post.id))
@login_required(login_url='/user/login')
def delete(request, num):
    post = Board.objects.get(Q(id=num))
    post.delete()
    return redirect('/board/list/')

def list(request):
    posts = Board.objects.all().order_by('-id')

    return render(request, 'board/list.html', {'posts': posts})

web2/user/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.

def signup(request):
    if request.method == 'POST':
        signupForm = UserCreationForm(request.POST)

        if signupForm.is_valid():
            signupForm.save()
            return redirect('/user/login')
    else:
        signupForm = UserCreationForm()
    return render(request, 'user/signup.html', {'signupForm':signupForm})

def login(request):
    if request.method == 'POST':
        loginForm = AuthenticationForm(request, request.POST)

        if loginForm.is_valid():
            auth_login(request, loginForm.get_user())
            return redirect('/board/list/')
        else:
            return redirect('/user/login')
    else:
        loginForm = AuthenticationForm()

    return render(request, 'user/login.html', {'loginForm':loginForm})

def logout(request):
    auth_logout(request)
    return redirect('/user/login')

web2/templates/board/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0",
    shrink-to-fit=no">
    <!-- <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    /> -->
    <link rel="stylesheet" href="/static/bootstrap.min.css" />
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

web2/templates/board/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
</head>
<body>
<div class="container" style="max-width:500px;">
	<form method="POST">
    {% csrf_token %}
    <label for="id_title">Title:</label><br/>
        {{ boardForm.title }}<br/>
    <label for="id_contents">Contents:</label><br/>
        {{ boardForm.contents }}<br/>
	  <input class="btn btn-dark rounded-pill col-12" type="submit" value="작성하기">
  </form>
</div>
</body>
</html>

web2/templates/board/create2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
  {% csrf_token %}
  {{ boardForm }}
  <input type="submit" value="작성">
</form>
</body>
</html>

web2/templates/board/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">

</head>
<body>


{% block content %}
<div class="row mt-5">
  <div class="col-12">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">글 번호</th>
          <th scope="col">제목</th>
          <th scope="col">아이디</th>
          <th scope="col">작성일</th>
        </tr>
      </thead>

      <tbody>
        <tr>
        {% if posts %}
            {% for post in posts %}
                <tr>
                    <td>{{ post.id }}</td>
                    <td><a href="/board/read/{{post.id}}">{{ post.title }} </td>
                    <td>{{ post.writer }}</td>
                    <td>{{ post.create_date }}</td>
                </tr>

            {% endfor %}
        {% endif %}
        </tr>
        </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-12">
      <a href="/board/create">
    <button class="btn btn-primary" >글쓰기</button>
  </div>
</div>
{% endblock %}
</html>

web2/templates/board/list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table>
        <thead>
            <th>글 번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일시</th>
        </thead>

        {% if posts %}
            {% for post in posts %}
                <tr>
                    <td>{{ post.id }}</td>
                    <td>{{ post.writer }}</td>
                    <td>{{ post.title }}</td>
                    <td>{{ post.create_date }}</td>
                </tr>

                <tr>
                    {% if request.user == post.writer %}
                    <td><a href="/board/update/{{post.id}}">
                        <button>수정</button>
                    </a></td>
                    <td><a href="/board/delete/{{post.id}}">
                        <button>삭제</button>
                    </a></td>
                    {% endif %}
                    <td><a href="/board/list/">
                        <button>목록</button>
                    </a></td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>
</body>
</html>

web2/templates/board/read.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
</head>
<body>
{% block content %}
<div class="row mt-5">
  <div class="col-12">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">글 번호</th>
          <th scope="col">제목</th>
          <th scope="col">아이디</th>
          <th scope="col">작성일</th>
          <th scope="col">내용</th>
        </tr>
      </thead>

      <tbody>
        <tr>
        {% if post %}
                <tr>
                    <td>{{ post.id }}</td>
                    <td>{{ post.title }} </td>
                    <td>{{ post.writer }}</td>
                    <td>{{ post.create_date }}</td>
                    <td>{{ post.contents }}</td>
                </tr>
        {% endif %}
        </tr>
        </tbody>
    </table>
  </div>
</div>
{% if request.user == post.writer %}
<div class="row">
  <div class="col-12">
      <a href="/board/update/{{post.id}}">
    <button class="btn btn-primary" >수정</button>
      <a href="/board/delete/{{post.id}}">
    <button class="btn btn-primary" >삭제</button>
      <a href="/board/list/">
    <button class="btn btn-primary" >목록</button>
  </div>

</div>
{% endif %}
{% endblock %}
</body>
</html>

web2/templates/board/read2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
</head>
<body>
<table>
        <thead>
            <th>글 번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </thead>

        {% if post %}

                <tr>
                    <td>{{ post.id }}</td>
                    <td>{{ post.title }}</td>
                    <td>{{ post.contents }}</td>
                    <td>{{ post.create_date }}</td>
                </tr>

        {% endif %}
    </table>
</body>
</html>

web2/templates/board/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

result 페이지 입니다.

</body>
</html>

web2/templates/board/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
</head>
<body>
<div class="container" style="max-width:500px;">
   <form method="POST">
       {% csrf_token %}
    <label for="id_title">Title:</label><br/>
        {{ boardForm.title }}<br/>
    <label for="id_contents">Contents:</label><br/>
        {{ boardForm.contents }}<br/>
	  <input class="btn btn-dark rounded-pill col-12" type="submit" value="수정하기">
  </form>
</div>
</body>
</html>

web2/templates/board/update2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ boardForm }}
  <button>수정</button>

</form>

</body>
</html>

web2/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

web2/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
테스트
</body>
</html>

web2/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>로그인</h1>

<form method="POST">
  {% csrf_token %}

  {{ loginForm }}
  <input type="submit" value="로그인"/>

</form>

</body>
</html>

web2/templates/user/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>로그인</h1>

<form method="POST">
  {% csrf_token %}

  {{ loginForm.id.id_for_label }}
  <input type="submit" value="로그인"/>

</form>

</body>
</html>

web2/templates/user/login3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="js/style.js"></script>


</head>
<body>
<div class="form signup">
  <div class="form-header">
    <div class="show-signup">Sign In</div>
    <div class="show-signin">Sign Up</div>
    <div class="show-reset">Reset</div>
  </div>
  <div class="arrow"></div>
  <div class="form-elements">
    <div class="form-element">
      <input type="text" placeholder="Username">
    </div>
    <div class="form-element">
      <input type="password" placeholder="Password">
    </div>
    <div class="form-element">
      <input type="password" placeholder="Confirm password">
    </div>
    <div class="form-element">
      <button id="submit-btn">Sign In</button>
    </div>
  </div>
</div>

</body>
</html>

web2/templates/user/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="js/style.js"></script>


</head>
<body>
<div class="form signup">
  <div class="form-header">
    <div class="show-signin"><a href="/user/login" style="text-decoration:none; color:white">Sign In</a></div>
    <div class="show-signup" style = "color: #f1575b">Sign Up</div>
  </div>

<form method="POST">
    {% csrf_token %}
  <div class="form-elements">
    <div class="form-element">
      <input type="text" placeholder="Username" id="{{ signupForm.username }}">
    </div>
    <div class="form-element">
      <input type="password" placeholder="Password" id="{{ signupForm.password1 }}">
    </div>
    <div class="form-element">
      <input type="password" placeholder="Confirm password" id="{{ signupForm.password2 }}">
    </div>
    <div class="form-element">
      <button id="submit-btn">Sign Up</button>
    </div>
  </div>
</form>
</div>

</body>
</html>

web2/templates/user/signup2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>회원가입</h1>

<form method="POST">
    {% csrf_token %}
    {{ signupForm }}
    <input type="submit" name="Submit"/>
</form>
</body>
</html>